blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('<int:blog_id>', views.detail, name='detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from skills import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

skills/models.py
from django.db import models


class Skills(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='skills/image/')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, "blog/details.html", {'blog': blog})

skills/views.py
from django.shortcuts import render
from .models import Skills


def index(request):
    projects = Skills.objects.all()
    return render(request, 'skills/index.html', {'projects': projects})

blog/templates/blog/blogs.html
{% extends 'skills/base.html' %}

{% block content %}
<h1>Блог</h1>
<h2 class="count">Постов: {{ blogs.count }}</h2>
{% for blog in blogs %}
<div class="element element2">
    <h2 class="top"><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h2>
    <div class="blog_text">
        <h5>{{ blog.date|date:'d.m.Y'}}</h5>
        <div>{{ blog.description|truncatechars:360|striptags }}</div>
    </div>
</div>
{% endfor %}

{% endblock content %}

blog/templates/blog/details.html
{% extends 'skills/base.html' %}

{% block content %}
<div class="detail">
 <h1>{{ blog.title }}</h1>
 <h2>-- {{ blog.date|date:'j E Y'}} --</h2>
 {{ blog.description|safe }}
</div>

{% endblock content %}

skills/templates/skills/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="icon" type="image/x-icon" href="{% static 'skill/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="menu">
        <div class="wrap">
            <div class="logo">
                <a href="{% url 'index' %}">
                    <img src="{% static 'skills/logo.png' %}" alt="">
                </a>
            </div>
            <ul>
                <li><a href="{% url 'index' %}">Главная</a></li>
                <li><a href="{% url 'blog:blogs' %}">Блог</a></li>
                <li><a href="{% static 'skills/resume.pdf' %}" target="_blank">Резюме</a></li>
            </ul>
        </div>
    </div>
    <div class="content">
        <div class="wrap">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</body>
</html>

skills/templates/skills/index.html
{% extends 'skills/base.html' %}

{% block content %}
{% load static %}
<h1>Портфолио разработчика</h1>
<div class="img">
    <img src="{% static 'skills/wc.jpg' %}" alt="">
</div>
<h2>Стек технологий:</h2>
<div class="block">
    {% for project in projects %}
    <div class="element">
        <div><img src="{{ project.image.url}}" alt=""></div>
        <div class="text">
            <h2><a href="{{project.url}}" target="_blank">{{project.title}}</a></h2>
            <p>{{project.description}}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}